# Create Logistic regression for predicting absenteeism

## importing libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

,Reason_group1,Reason_group2,Reason_group3,Reason_group4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Day of Week
0,0,0,0,1,289,36,33,239.554,30,0,2,1,4,7,Tuesday
1,0,0,0,0,118,13,50,239.554,31,0,1,0,0,7,Tuesday
2,0,0,0,1,179,51,38,239.554,31,0,0,0,2,7,Wednesday
3,1,0,0,0,279,5,39,239.554,24,0,2,0,4,7,Thursday
4,0,0,0,1,289,36,33,239.554,30,0,2,1,2,7,Thursday

## create the targets

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
# 3 hours is our cutoff line above it is absent and less than that is not 
targets= np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [6]:
targets.sum()/targets.shape[0] #roughly balanced

0.45571428571428574

In [7]:
data_preprocessed['Excessive Absenteesism'] = data_preprocessed['Absenteeism Time in Hours'].apply(lambda x : 1 if x>3.0 else 0)

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of Week','Daily Work Load Average','Distance to Work'],axis=1)

In [9]:
data_with_targets.head()

,Reason_group1,Reason_group2,Reason_group3,Reason_group4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month,Excessive Absenteesism
0,0,0,0,1,289,33,30,0,2,1,7,1
1,0,0,0,0,118,50,31,0,1,0,7,0
2,0,0,0,1,179,38,31,0,0,0,7,0
3,1,0,0,0,279,39,24,0,2,0,7,1
4,0,0,0,1,289,33,30,0,2,1,7,0

In [10]:
#data_with_targets['Day of Week'] = data_with_targets['Day of Week'].map({'Monday':0,'Tuesday':1,'Wednesday':2,'Thursday':3,'Friday':4,'Saturday':5,'Sunday':6})

In [11]:
data_with_targets

,Reason_group1,Reason_group2,Reason_group3,Reason_group4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month,Excessive Absenteesism
0,0,0,0,1,289,33,30,0,2,1,7,1
1,0,0,0,0,118,50,31,0,1,0,7,0
2,0,0,0,1,179,38,31,0,0,0,7,0
3,1,0,0,0,279,39,24,0,2,0,7,1
4,0,0,0,1,289,33,30,0,2,1,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,179,40,22,1,2,0,5,1
696,1,0,0,0,225,28,24,0,1,2,5,0
697,1,0,0,0,330,28,25,1,0,0,5,1
698,0,0,0,1,235,32,25,1,0,0,5,0
699,0,0,0,1,291,40,25,0,1,1,5,0

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
data_with_targets.iloc[:,0:14]

,Reason_group1,Reason_group2,Reason_group3,Reason_group4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month,Excessive Absenteesism
0,0,0,0,1,289,33,30,0,2,1,7,1
1,0,0,0,0,118,50,31,0,1,0,7,0
2,0,0,0,1,179,38,31,0,0,0,7,0
3,1,0,0,0,279,39,24,0,2,0,7,1
4,0,0,0,1,289,33,30,0,2,1,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,179,40,22,1,2,0,5,1
696,1,0,0,0,225,28,24,0,1,2,5,0
697,1,0,0,0,330,28,25,1,0,0,5,1
698,0,0,0,1,235,32,25,1,0,0,5,0
699,0,0,0,1,291,40,25,0,1,1,5,0

In [14]:
data_with_targets.iloc[:,:-1]

,Reason_group1,Reason_group2,Reason_group3,Reason_group4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month
0,0,0,0,1,289,33,30,0,2,1,7
1,0,0,0,0,118,50,31,0,1,0,7
2,0,0,0,1,179,38,31,0,0,0,7
3,1,0,0,0,279,39,24,0,2,0,7
4,0,0,0,1,289,33,30,0,2,1,7
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,179,40,22,1,2,0,5
696,1,0,0,0,225,28,24,0,1,2,5
697,1,0,0,0,330,28,25,1,0,0,5
698,0,0,0,1,235,32,25,1,0,0,5
699,0,0,0,1,291,40,25,0,1,1,5

In [15]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [16]:
from sklearn.preprocessing import StandardScaler

class CustomScaler:
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns
        self.mean_ = None

    def fit(self, X, y=None):
        self.mean_ = X[self.columns].mean()
        self.scaler.fit(X[self.columns], y)
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

    def fit_transform(self, X, y=None, copy=None):
        return self.fit(X, y).transform(X, y, copy)

In [17]:
unscaled_inputs.columns.values

array(['Reason_group1', 'Reason_group2', 'Reason_group3', 'Reason_group4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month'], dtype=object)

In [18]:
columns_to_omit = ['Reason_group1', 'Reason_group2', 'Reason_group3', 'Reason_group4','Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [20]:
scaled_inputs = absenteeism_scaler.fit_transform(unscaled_inputs)
scaled_inputs

,Reason_group1,Reason_group2,Reason_group3,Reason_group4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month
0,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
1,0,0,0,0,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,0.182726
2,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
3,1,0,0,0,0.854936,0.405184,-0.643782,0,0.880469,-0.589690,0.182726
4,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690,-0.388293
696,1,0,0,0,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663,-0.388293
697,1,0,0,0,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690,-0.388293
698,0,0,0,1,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.388293
699,0,0,0,1,1.036026,0.562059,-0.408580,0,-0.019280,0.268487,-0.388293

In [21]:
scaled_inputs.shape

(700, 11)

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,test_size=0.2,random_state=42)

In [23]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)

In [24]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
reg = LogisticRegression()

In [27]:
reg.fit(x_train,y_train)

LogisticRegression()

In [28]:
reg.score(x_train,y_train)

0.7732142857142857

# Manually check the accuracy

In [29]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [30]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [31]:
np.sum((model_outputs==y_train))

433

In [32]:
model_outputs.shape[0]

560

In [33]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7732142857142857

## finding the intercept and coefficients

In [34]:
reg.intercept_

array([-1.70293007])

In [35]:
reg.coef_

array([[ 2.9136209 ,  0.75484748,  3.09891742,  0.96486444,  0.65018629,
        -0.25112372,  0.25250206, -0.24004052,  0.39910996, -0.29389223,
         0.07441017]])

In [36]:
unscaled_inputs.columns.values

array(['Reason_group1', 'Reason_group2', 'Reason_group3', 'Reason_group4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month'], dtype=object)

In [37]:
feature_name = unscaled_inputs.columns.values

In [38]:
summary_table = pd.DataFrame(columns=['feature name'],data=feature_name)
summary_table['coefficient'] = np.transpose(reg.coef_)
summary_table

              feature name  coefficient
0            Reason_group1     2.913621
1            Reason_group2     0.754847
2            Reason_group3     3.098917
3            Reason_group4     0.964864
4   Transportation Expense     0.650186
5                      Age    -0.251124
6          Body Mass Index     0.252502
7                Education    -0.240041
8                 Children     0.399110
9                     Pets    -0.293892
10                   Month     0.074410

In [39]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

              feature name  coefficient
0                Intercept    -1.702930
1            Reason_group1     2.913621
2            Reason_group2     0.754847
3            Reason_group3     3.098917
4            Reason_group4     0.964864
5   Transportation Expense     0.650186
6                      Age    -0.251124
7          Body Mass Index     0.252502
8                Education    -0.240041
9                 Children     0.399110
10                    Pets    -0.293892
11                   Month     0.074410

## Interpreting the coefficients

In [40]:
# larger the coefficient more the weight (more important feature)
summary_table['odds_ratio'] = np.exp(summary_table.coefficient)

In [41]:
summary_table.sort_values('odds_ratio',ascending=False)

              feature name  coefficient  odds_ratio
3            Reason_group3     3.098917   22.173933
1            Reason_group1     2.913621   18.423387
4            Reason_group4     0.964864    2.624432
2            Reason_group2     0.754847    2.127287
5   Transportation Expense     0.650186    1.915898
9                 Children     0.399110    1.490498
7          Body Mass Index     0.252502    1.287242
11                   Month     0.074410    1.077249
8                Education    -0.240041    0.786596
6                      Age    -0.251124    0.777926
10                    Pets    -0.293892    0.745357
0                Intercept    -1.702930    0.182149

## Testing the model

In [42]:
reg.score(x_test,y_test)

0.7714285714285715

In [43]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba # first column shows probability of assigning 0 and second shows the same for 1

array([[0.82957126, 0.17042874],
       [0.85163998, 0.14836002],
       [0.79779583, 0.20220417],
       [0.593212  , 0.406788  ],
       [0.57365867, 0.42634133],
       [0.08041824, 0.91958176],
       [0.67595129, 0.32404871],
       [0.35568421, 0.64431579],
       [0.7163203 , 0.2836797 ],
       [0.74005176, 0.25994824],
       [0.86456635, 0.13543365],
       [0.67492732, 0.32507268],
       [0.26570587, 0.73429413],
       [0.44925745, 0.55074255],
       [0.72600362, 0.27399638],
       [0.4921817 , 0.5078183 ],
       [0.89459595, 0.10540405],
       [0.21441612, 0.78558388],
       [0.86703473, 0.13296527],
       [0.58401659, 0.41598341],
       [0.73026575, 0.26973425],
       [0.74411785, 0.25588215],
       [0.68178599, 0.31821401],
       [0.67957102, 0.32042898],
       [0.86082189, 0.13917811],
       [0.16084394, 0.83915606],
       [0.59430082, 0.40569918],
       [0.59675531, 0.40324469],
       [0.75996029, 0.24003971],
       [0.59941268, 0.40058732],
       [0.88259371, 0.11740629],
       [0.85872932, 0.14127068],
       [0.40060567, 0.59939433],
       [0.43876863, 0.56123137],
       [0.72175731, 0.27824269],
       [0.35008369, 0.64991631],
       [0.68178599, 0.31821401],
       [0.86628584, 0.13371416],
       [0.14526315, 0.85473685],
       [0.80081857, 0.19918143],
       [0.481567  , 0.518433  ],
       [0.74814198, 0.25185802],
       [0.36548029, 0.63451971],
       [0.87185724, 0.12814276],
       [0.7751183 , 0.2248817 ],
       [0.27402099, 0.72597901],
       [0.23110139, 0.76889861],
       [0.11610647, 0.88389353],
       [0.69093227, 0.30906773],
       [0.86946491, 0.13053509],
       [0.74005176, 0.25994824],
       [0.68637723, 0.31362277],
       [0.57365867, 0.42634133],
       [0.06716186, 0.93283814],
       [0.86128702, 0.13871298],
       [0.7751183 , 0.2248817 ],
       [0.02363741, 0.97636259],
       [0.72175731, 0.27824269],
       [0.12814637, 0.87185363],
       [0.77499893, 0.22500107],
       [0.40729246, 0.59270754],
       [0.88037432, 0.11962568],
       [0.50097671, 0.49902329],
       [0.35568421, 0.64431579],
       [0.86456635, 0.13543365],
       [0.58649   , 0.41351   ],
       [0.31999278, 0.68000722],
       [0.94196914, 0.05803086],
       [0.73020934, 0.26979066],
       [0.49490041, 0.50509959],
       [0.74005176, 0.25994824],
       [0.75996029, 0.24003971],
       [0.30171486, 0.69828514],
       [0.68637723, 0.31362277],
       [0.86583487, 0.13416513],
       [0.35008369, 0.64991631],
       [0.57884631, 0.42115369],
       [0.77879983, 0.22120017],
       [0.73020934, 0.26979066],
       [0.55447299, 0.44552701],
       [0.08041824, 0.91958176],
       [0.1115055 , 0.8884945 ],
       [0.87349771, 0.12650229],
       [0.75212391, 0.24787609],
       [0.88259371, 0.11740629],
       [0.29265337, 0.70734663],
       [0.75212391, 0.24787609],
       [0.10410457, 0.89589543],
       [0.26838419, 0.73161581],
       [0.69093227, 0.30906773],
       [0.80120132, 0.19879868],
       [0.46025448, 0.53974552],
       [0.69551114, 0.30448886],
       [0.72175731, 0.27824269],
       [0.55993286, 0.44006714],
       [0.14526315, 0.85473685],
       [0.50118337, 0.49881663],
       [0.0651031 , 0.9348969 ],
       [0.34472285, 0.65527715],
       [0.26987145, 0.73012855],
       [0.748074  , 0.251926  ],
       [0.35981166, 0.64018834],
       [0.7751183 , 0.2248817 ],
       [0.23771761, 0.76228239],
       [0.84893561, 0.15106439],
       [0.39044745, 0.60955255],
       [0.16666187, 0.83333813],
       [0.80081857, 0.19918143],
       [0.8730675 , 0.1269325 ],
       [0.33101133, 0.66898867],
       [0.36548029, 0.63451971],
       [0.35009193, 0.64990807],
       [0.46507278, 0.53492722],
       [0.67024898, 0.32975102],
       [0.23766573, 0.76233427],
       [0.44460846, 0.55539154],
       [0.71105532, 0.28894468],
       [0.08693086, 0.91306914],
       [0.55469149, 0.44530851],
       [0.13560542, 0.86439458],
       [0.75606342, 0.24393658],
       [0.22453259, 0.77546741],
       [0.2273479 , 0.7726521 ],
       [0.26152625, 0.73847375],
       [0.26781205, 0.73218795],
       [0.71401173, 0.28598827],
       [0.7751183 , 0.2248817 ],
       [0.74404915, 0.25595085],
       [0.32930828, 0.67069172],
       [0.86380575, 0.13619425],
       [0.68178599, 0.31821401],
       [0.82347956, 0.17652044],
       [0.21276697, 0.78723303],
       [0.50118337, 0.49881663],
       [0.69093227, 0.30906773],
       [0.06382192, 0.93617808],
       [0.48959053, 0.51040947],
       [0.34527366, 0.65472634],
       [0.58401659, 0.41598341],
       [0.85613235, 0.14386765]])

In [46]:
predicted_proba[:,1]

array([0.17042874, 0.14836002, 0.20220417, 0.406788  , 0.42634133,
       0.91958176, 0.32404871, 0.64431579, 0.2836797 , 0.25994824,
       0.13543365, 0.32507268, 0.73429413, 0.55074255, 0.27399638,
       0.5078183 , 0.10540405, 0.78558388, 0.13296527, 0.41598341,
       0.26973425, 0.25588215, 0.31821401, 0.32042898, 0.13917811,
       0.83915606, 0.40569918, 0.40324469, 0.24003971, 0.40058732,
       0.11740629, 0.14127068, 0.59939433, 0.56123137, 0.27824269,
       0.64991631, 0.31821401, 0.13371416, 0.85473685, 0.19918143,
       0.518433  , 0.25185802, 0.63451971, 0.12814276, 0.2248817 ,
       0.72597901, 0.76889861, 0.88389353, 0.30906773, 0.13053509,
       0.25994824, 0.31362277, 0.42634133, 0.93283814, 0.13871298,
       0.2248817 , 0.97636259, 0.27824269, 0.87185363, 0.22500107,
       0.59270754, 0.11962568, 0.49902329, 0.64431579, 0.13543365,
       0.41351   , 0.68000722, 0.05803086, 0.26979066, 0.50509959,
       0.25994824, 0.24003971, 0.69828514, 0.31362277, 0.13416513,
       0.64991631, 0.42115369, 0.22120017, 0.26979066, 0.44552701,
       0.91958176, 0.8884945 , 0.12650229, 0.24787609, 0.11740629,
       0.70734663, 0.24787609, 0.89589543, 0.73161581, 0.30906773,
       0.19879868, 0.53974552, 0.30448886, 0.27824269, 0.44006714,
       0.85473685, 0.49881663, 0.9348969 , 0.65527715, 0.73012855,
       0.251926  , 0.64018834, 0.2248817 , 0.76228239, 0.15106439,
       0.60955255, 0.83333813, 0.19918143, 0.1269325 , 0.66898867,
       0.63451971, 0.64990807, 0.53492722, 0.32975102, 0.76233427,
       0.55539154, 0.28894468, 0.91306914, 0.44530851, 0.86439458,
       0.24393658, 0.77546741, 0.7726521 , 0.73847375, 0.73218795,
       0.28598827, 0.2248817 , 0.25595085, 0.67069172, 0.13619425,
       0.31821401, 0.17652044, 0.78723303, 0.49881663, 0.30906773,
       0.93617808, 0.51040947, 0.65472634, 0.41598341, 0.14386765])

## Saving the model

In [47]:
import pickle

In [48]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [49]:
with open('absenteeism_scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)

In [51]:
import sklearn

In [52]:
print(sklearn.__version__)

1.4.2